---
title: "Temp.HT"
author: "Alene Onion"
date: "January 1, 2019"
output:
  html_document:
    toc: true
    toc_depth: 6
    toc_float: true
---

```{r setuTHT, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#file.copy("sections/images", ".", recursive = TRUE)
```

## Holding Time
The analysis date - sample date should not exceed holding time limits in the holding time look up table.    
```{r message=FALSE, warning=FALSE, results='asis'}
# Load holding times reference table
# Updated holding times table on 11/5/19 to remove 12 hour buffers
# Udpated holding times again on 1/31/20 to add 1 hr buffer for HTs of 72 hours and below, and 1 day for those beyond (as per 1/29/20 email with Vicky Collam, ALS Quality Manager)
holdingtimes <- read.csv("data/Holding.Times_v3.csv")
holdingtimes$Holding<-as.numeric(holdingtimes$Holding)

# Make simpler holding time lookup table with only two columns
holdingtimes <- unique(holdingtimes[c("chemical_name","Holding")])
# Merge data frame and holding times lookup table
HT <- merge(HT, holdingtimes, by=c("chemical_name"), all.x = TRUE)

if (sum(is.na(HT$Holding)) > 0) {
  # cat("NOT ALL PARAMS JOINED WITH HOLDING TIMES") 
  stop("NOT ALL PARAMETERS JOINED WITH HOLDING TIMES TABLE")   
}

rm(holdingtimes)

#format dates
library(lubridate)

#Added on 2/8/19 to account for new handing of date formatting at beginning of script (QAQC.Rmd)
HT$sample_date<-format(HT$sample_date, "%m-%d-%Y %H:%M")
HT$analysis_date<-format(HT$analysis_date, "%m-%d-%Y %H:%M")

HT$sample_date<-mdy_hm(HT$sample_date)
HT$analysis_date<-mdy_hm(HT$analysis_date)
# Calculate difference between sample datetimes and analysis datetimes (actual holding times)
HT$HTactual <- difftime(HT$analysis_date ,HT$sample_date , units = c("hours"))

# Calculate holding time exceedances 
HT$HTexceed_hrs <- HT$HTactual - HT$Holding
HT$HTpass <- HT$HTactual - HT$Holding
HT$HTpass <- as.numeric(HT$HTpass)
HT$HTpass<-ifelse(HT$HTpass>0,"R","A")
HT<-unique(HT[c('chemical_name','sys_sample_code','lab_sdg','sample_date','analysis_date','Holding','HTactual','HTexceed_hrs','short','HTpass')])
#add these flags to the larger data set
# data$sample_date<-as.Date(data$sample_date,"%m/%d/%Y")
data<-merge(data,HT,by=c('sys_sample_code','chemical_name','short','sample_date','lab_sdg'),all=TRUE)
data<-data[!is.na(data$chemical_name),]
```

### Holding Time Rejected samples
```{r message=FALSE, warning=FALSE, results='asis', fig.height=5.5}
#plotting the sample failures
#count fails and passes
# library(plyr)
HTfails<-count(HT[c('short','HTpass')])
names(HTfails)[names(HTfails)=='HTpass']<-'legend'

library(ggplot2)
library(ggpubr)
theme_set(theme_pubr())

 print(HTfails<-(ggplot() +
    geom_col(data=HTfails,aes(short,freq,fill=legend)) +
      coord_flip() +
      theme(axis.title.x = element_blank(),axis.title.y = element_blank()) +
      scale_fill_manual(values = c("A" = "#00BFC4", "R" = "#F8766D"), na.value = "gray")))

 if (sum(grepl("R", HT$HTpass)) > 0) {
   knitr::kable(HT %>% filter(HTpass=="R"))
 } else {cat("\nNo holding time failures.")}
 
# rm(list=c('HTfails','HT'))
```

